[project]
name = "mcp-client"
version = "0.1.0"
description = "A simple MCP client"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "anthropic>=0.72.0",
    "mcp>=1.21.0",
    "python-dotenv>=1.2.1",
]
